#!/bin/sh

alias vim="nvim"

for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	sha="shasum -a 256" \
	yt="youtube-dl --add-metadata -i" \
	ex="atool -x" \
#	yta="yt -x -f bestaudio/best" \
#	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -AhN --color=auto --group-directories-first --hyperlink" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"
	config="source config"
alias \
	ka="killall" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" 

# Git
alias \
	g="git" \
	gco="git checkout" \
	gc="git commit" \
	clone="git clone"

alias \
	hg="history|grep" \
	now='"date +"%T"' \
	today='date +"%m/%d/%Y"' \
	ipe='curl ipinfo.io/ip' \
	cfg='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME' \
	theme='kitty +kitten themes --reload-in=all' \
	standby='systemctl suspend'

alias \
	loopback="pw-loopback -C alsa_input.pci-0000_0d_00.4.analog-stereo"

[ -e "$XDG_CONFIG_HOME/shell/aliasrc.local" ] && source "$XDG_CONFIG_HOME/shell/aliasrc.local"
