#!/bin/sh

alias vim="nvim"

for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	sha="shasum -a 256"
	yt="youtube-dl --add-metadata -i" \
#	yta="yt -x -f bestaudio/best" \
#	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

alias \
	ka="killall" \
	g="git" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \

alias \
	hg="history|grep" \
	now='"date +"%T"' \
	today='date +"%m/%d/%Y"' \
	ipe='curl ipinfo.io/ip' \
	cfg='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

[ $(hostname) = mbpcts-dock.berlin.abs-rz.de ] && source $XDG_CONFIG_HOME/shell/aliasrc.macos