#!/bin/sh

alias vim="nvim"

for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	sha="shasum -a 256" \
	yt="youtube-dl --add-metadata -i" \
#	yta="yt -x -f bestaudio/best" \
#	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -AhN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

alias \
	ka="killall" \
	g="git" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" 

alias \
	hg="history|grep" \
	now='"date +"%T"' \
	today='date +"%m/%d/%Y"' \
	ipe='curl ipinfo.io/ip' \
	cfg='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME' \
	standby='systemctl suspend'

alias \
	loopback="pw-loopback -C alsa_input.pci-0000_0d_00.4.analog-stereo"

alias \
	cfgi3="$EDITOR ~/.config/i3/config" \
	cfgxprofile="$EDITOR ~/.config/x11/profile" \
	cfgprofile="$EDITOR ~/.config/shell/profile && source ~/.config/shell/profile" \
	cfgalias="$EDITOR ~/.config/shell/aliasrc && source ~/.config/shell/aliasrc" \
	cfgzsh="$EDITOR ~/.config/zsh/.zshrc && source ~/.config/zsh/.zshrc" \
	cfgvim="$EDITOR ~/.config/nvim/init.vim" \
	cfgkitty="$EDITOR ~/.config/kitty/kitty.conf" \
	cfgpicom="$EDITOR ~/.config/picom/picom.conf" \
	cfgi3blocks="$EDITOR ~/.config/i3blocks/config" 


[ -e "$XDG_CONFIG_HOME/shell/aliasrc.local" ] && source "$XDG_CONFIG_HOME/shell/aliasrc.local"
