#!/bin/sh
export PATH=$PATH:$HOME/.local/bin:$HOME/.local/bin/status
export EDITOR="nvim"
export VISUAL="vim"
export BROWSER="google-chrome-stable"
export WEATHER="Mitte"
export LESS='-R'
export HISTCONTROL=ignoreboth # no duplicates in history

export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"


# Gaming specific paths
export MINECRAFT="/home/yankas/.local/share/gdlauncher_next/instances/"
export TS4_MODS="/home/yankas/.local/share/wine/Electronic Arts/The Sims 4/Mods"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export GCM_CREDENTIAL_STORE=gpg
export GTK2_RC_FILES=~/.config/gtk-2.0/gtkrc-2.0
export SSH_TTY=$(tty)

export LIBVIRT_DFEAULT_URI="qemu://system"

export LESS_TERMCAP_mb=$(tput bold; tput setaf 2) # green
export LESS_TERMCAP_md=$(tput bold; tput setaf 6) # cyan
export LESS_TERMCAP_me=$(tput sgr0)
export LESS_TERMCAP_so=$(tput bold; tput setaf 3; tput setab 4) # yellow on blue
export LESS_TERMCAP_se=$(tput rmso; tput sgr0)
export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 7) # white
export LESS_TERMCAP_ue=$(tput rmul; tput sgr0)
export LESS_TERMCAP_mr=$(tput rev)
export LESS_TERMCAP_mh=$(tput dim)
export LESS_TERMCAP_ZN=$(tput ssubm)
export LESS_TERMCAP_ZV=$(tput rsubm)
export LESS_TERMCAP_ZO=$(tput ssupm)
export LESS_TERMCAP_ZW=$(tput rsupm)

export LF_ICONS="di=📁:\
fi=📃:\
tw=🤝:\
ow=📂:\
ln=⛓:\
or=❌:\
ex=🎯:\
*.txt=✍:\
*.mom=✍:\
*.me=✍:\
*.ms=✍:\
*.png=🖼:\
*.webp=🖼:\
*.ico=🖼:\
*.jpg=📸:\
*.jpe=📸:\
*.jpeg=📸:\
*.gif=🖼:\
*.svg=🗺:\
*.tif=🖼:\
*.tiff=🖼:\
*.xcf=🖌:\
*.html=🌎:\
*.xml=📰:\
*.gpg=🔒:\
*.css=🎨:\
*.pdf=📚:\
*.djvu=📚:\
*.epub=📚:\
*.csv=📓:\
*.xlsx=📓:\
*.tex=📜:\
*.md=📘:\
*.r=📊:\
*.R=📊:\
*.rmd=📊:\
*.Rmd=📊:\
*.m=📊:\
*.mp3=🎵:\
*.opus=🎵:\
*.ogg=🎵:\
*.m4a=🎵:\
*.flac=🎼:\
*.wav=🎼:\
*.mkv=🎥:\
*.mp4=🎥:\
*.webm=🎥:\
*.mpeg=🎥:\
*.avi=🎥:\
*.mov=🎥:\
*.mpg=🎥:\
*.wmv=🎥:\
*.m4b=🎥:\
*.flv=🎥:\
*.zip=📦:\
*.rar=📦:\
*.7z=📦:\
*.tar.gz=📦:\
*.z64=🎮:\
*.v64=🎮:\
*.n64=🎮:\
*.gba=🎮:\
*.nds=🎮:\
*.nes=🎮:\
*.gdi=🎮:\
*.nsp=🎮:\
*.xci=🎮:\
*.1=ℹ:\
*.nfo=ℹ:\
*.info=ℹ:\
*.log=📙:\
*.iso=📀:\
*.img=📀:\
*.bib=🎓:\
*.ged=👪:\
*.part=💔:\
*.torrent=🔽:\
*.jar=♨:\
*.java=♨:\
*.exe=🪟:\
*.ml=🐫:\
*.php=🐘:\
*.pl=⛔:\
*.c=🇨:\
*.h=🇭:\
*.sh=⚙️:\
*.zsh=⚙️:\
*profile=⚙️:\
*xprofile=⚙️:\
*.zshrc=⚙️:\
*aliasrc=⚙️:\
*.xinitrc=⚙️:\
*.ml=🐫:\
*.php=🐘:\
*.pl=⛔:\
*.c=🇨:\
*.h=🇭:\
*.sh=⚙️:\
*.zsh=⚙️:\
*profile=⚙️:\
*xprofile=⚙️:\
*.zshrc=⚙️:\
*aliasrc=⚙️:\
*.xinitrc=⚙️"
[ -e $HOME/.opam/opam-init/init.sh ] && source $HOME/.opam/opam-init/init.sh 
#[[ $(fgconsole 2>/dev/null) == 1 ]] && exec startx --vt1


[ -e "$XDG_CONFIG_HOME/shell/profile.local" ] && source "$XDG_CONFIG_HOME/shell/profile.local"

