#!/bin/sh

export PATH=$PATH:$HOME/.local/bin

export EDITOR="nvim"
export VISUAL="vim"
export BROWSER="google-chrome-stable"
export WEATHER="Mitte"

export LESS='-R'

export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export LIBVIRT_DFEAULT_URI="qemu://system"


# List of lf icons:
export LF_ICONS="di=📁:\
fi=📃:\
tw=🤝:\
ow=📂:\
ln=⛓:\
or=❌:\
ex=🎯:\
*.txt=✍:\
*.mom=✍:\
*.me=✍:\
*.ms=✍:\
*.png=🖼:\
*.webp=🖼:\
*.ico=🖼:\
*.jpg=📸:\
*.jpe=📸:\
*.jpeg=📸:\
*.gif=🖼:\
*.svg=🗺:\
*.tif=🖼:\
*.tiff=🖼:\
*.xcf=🖌:\
*.html=🌎:\
*.xml=📰:\
*.gpg=🔒:\
*.css=🎨:\
*.pdf=📚:\
*.djvu=📚:\
*.epub=📚:\
*.csv=📓:\
*.xlsx=📓:\
*.tex=📜:\
*.md=📘:\
*.r=📊:\
*.R=📊:\
*.rmd=📊:\
*.Rmd=📊:\
*.m=📊:\
*.mp3=🎵:\
*.opus=🎵:\
*.ogg=🎵:\
*.m4a=🎵:\
*.flac=🎼:\
*.wav=🎼:\
*.mkv=🎥:\
*.mp4=🎥:\
*.webm=🎥:\
*.mpeg=🎥:\
*.avi=🎥:\
*.mov=🎥:\
*.mpg=🎥:\
*.wmv=🎥:\
*.m4b=🎥:\
*.flv=🎥:\
*.zip=📦:\
*.rar=📦:\
*.7z=📦:\
*.tar.gz=📦:\
*.z64=🎮:\
*.v64=🎮:\
*.n64=🎮:\
*.gba=🎮:\
*.nds=🎮:\
*.nes=🎮:\
*.gdi=🎮:\
*.nsp=🎮:\
*.xci=🎮:\
*.1=ℹ:\
*.nfo=ℹ:\
*.info=ℹ:\
*.log=📙:\
*.iso=📀:\
*.img=📀:\
*.bib=🎓:\
*.ged=👪:\
*.part=💔:\
*.torrent=🔽:\
*.jar=♨:\
*.java=♨:\
*.exe=🪟:\
*.ml=🐫:\
*.php=🐘:\
*.pl=⛔:\
*.c=🇨:\
*.h=🇭:\
*.sh=⚙️:\
*.zsh=⚙️:\
*profile=⚙️:\
*xprofile=⚙️:\
*.zshrc=⚙️:\
*aliasrc=⚙️:\
*.xinitrc=⚙️:\
"


[ $(hostname) = absm-devel ] && source $HOME/.config/shell/profile.mdevel
[ $(hostname) = mbpcts-dock.berlin.abs-rz.de ] && source $XDG_CONFIG_HOME/shell/profile.macos

source $HOME/.opam/opam-init/init.sh
[[ $(fgconsole 2>/dev/null) == 1 ]] && exec startx --vt1
