#!/usr/bin/env sh

file=$1
[ -n "$2" ] && type=$2 || type="${1##*.}"

create () {
	echo "#!$1" > $file 	
}

case $type in
	py | python) create "/usr/bin/env python";;
	rb | ruby) create "/usr/bin/env ruby";;
	sh) create "/usr/bin/env sh";;
	zsh) create "/usr/bin/env zsh";;
	lua) create "/usr/bin/env lua";;
	fsi | fsx) create "/usr/bin/env dotnet fsi";;
	pl | pearl) create "/usr/bin/env pearl";;
	yml | yaml) create "---";;
	xml) create " <?xml version=\"1.0\" encoding=\"UTF-8\" ?>";;
esac